/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as LandingPageIndexRouteImport } from './routes/landing-page/index'
import { Route as InstructorIndexRouteImport } from './routes/instructor/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as StudentPaymentsIndexRouteImport } from './routes/student/payments/index'
import { Route as StudentEnrollmentsIndexRouteImport } from './routes/student/enrollments/index'
import { Route as StudentCoursesIndexRouteImport } from './routes/student/courses/index'
import { Route as StudentAssigmentsIndexRouteImport } from './routes/student/assigments/index'
import { Route as StudentAnalyticsIndexRouteImport } from './routes/student/analytics/index'
import { Route as InstructorStudentsIndexRouteImport } from './routes/instructor/students/index'
import { Route as InstructorLessonsIndexRouteImport } from './routes/instructor/lessons/index'
import { Route as InstructorEarningsIndexRouteImport } from './routes/instructor/earnings/index'
import { Route as InstructorCoursesIndexRouteImport } from './routes/instructor/courses/index'
import { Route as InstructorAssignmentsIndexRouteImport } from './routes/instructor/assignments/index'
import { Route as InstructorAnalyticsIndexRouteImport } from './routes/instructor/analytics/index'
import { Route as AdminStudentsIndexRouteImport } from './routes/admin/students/index'
import { Route as AdminProfileIndexRouteImport } from './routes/admin/profile/index'
import { Route as AdminInstructorsIndexRouteImport } from './routes/admin/instructors/index'
import { Route as AdminCoursesIndexRouteImport } from './routes/admin/courses/index'
import { Route as AdminAnalyticsIndexRouteImport } from './routes/admin/analytics/index'
import { Route as AdminAdminsIndexRouteImport } from './routes/admin/admins/index'
import { Route as StudentEnrollmentsIdRouteImport } from './routes/student/enrollments/$id'
import { Route as StudentCoursesIdRouteImport } from './routes/student/courses/$id'
import { Route as InstructorLessonsIdRouteImport } from './routes/instructor/lessons/$id'
import { Route as InstructorCoursesIdRouteImport } from './routes/instructor/courses/$id'
import { Route as AdminStudentsIdRouteImport } from './routes/admin/students/$id'
import { Route as AdminInstructorsIdRouteImport } from './routes/admin/instructors/$id'
import { Route as AdminCoursesIdRouteImport } from './routes/admin/courses/$id'
import { Route as AdminAuthRegisterRouteImport } from './routes/admin/auth/register'
import { Route as AdminAuthLoginRouteImport } from './routes/admin/auth/login'
import { Route as InstructorLessonsNewIndexRouteImport } from './routes/instructor/lessons/new/index'
import { Route as InstructorCoursesNewIndexRouteImport } from './routes/instructor/courses/new/index'
import { Route as StudentEnrollmentsLessonsIdRouteImport } from './routes/student/enrollments/lessons/$id'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingPageIndexRoute = LandingPageIndexRouteImport.update({
  id: '/landing-page/',
  path: '/landing-page/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorIndexRoute = InstructorIndexRouteImport.update({
  id: '/instructor/',
  path: '/instructor/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentPaymentsIndexRoute = StudentPaymentsIndexRouteImport.update({
  id: '/student/payments/',
  path: '/student/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentEnrollmentsIndexRoute = StudentEnrollmentsIndexRouteImport.update({
  id: '/student/enrollments/',
  path: '/student/enrollments/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCoursesIndexRoute = StudentCoursesIndexRouteImport.update({
  id: '/student/courses/',
  path: '/student/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAssigmentsIndexRoute = StudentAssigmentsIndexRouteImport.update({
  id: '/student/assigments/',
  path: '/student/assigments/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAnalyticsIndexRoute = StudentAnalyticsIndexRouteImport.update({
  id: '/student/analytics/',
  path: '/student/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorStudentsIndexRoute = InstructorStudentsIndexRouteImport.update({
  id: '/instructor/students/',
  path: '/instructor/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorLessonsIndexRoute = InstructorLessonsIndexRouteImport.update({
  id: '/instructor/lessons/',
  path: '/instructor/lessons/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorEarningsIndexRoute = InstructorEarningsIndexRouteImport.update({
  id: '/instructor/earnings/',
  path: '/instructor/earnings/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorCoursesIndexRoute = InstructorCoursesIndexRouteImport.update({
  id: '/instructor/courses/',
  path: '/instructor/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorAssignmentsIndexRoute =
  InstructorAssignmentsIndexRouteImport.update({
    id: '/instructor/assignments/',
    path: '/instructor/assignments/',
    getParentRoute: () => rootRouteImport,
  } as any)
const InstructorAnalyticsIndexRoute =
  InstructorAnalyticsIndexRouteImport.update({
    id: '/instructor/analytics/',
    path: '/instructor/analytics/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminStudentsIndexRoute = AdminStudentsIndexRouteImport.update({
  id: '/admin/students/',
  path: '/admin/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileIndexRoute = AdminProfileIndexRouteImport.update({
  id: '/admin/profile/',
  path: '/admin/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInstructorsIndexRoute = AdminInstructorsIndexRouteImport.update({
  id: '/admin/instructors/',
  path: '/admin/instructors/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesIndexRoute = AdminCoursesIndexRouteImport.update({
  id: '/admin/courses/',
  path: '/admin/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsIndexRoute = AdminAnalyticsIndexRouteImport.update({
  id: '/admin/analytics/',
  path: '/admin/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminsIndexRoute = AdminAdminsIndexRouteImport.update({
  id: '/admin/admins/',
  path: '/admin/admins/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentEnrollmentsIdRoute = StudentEnrollmentsIdRouteImport.update({
  id: '/student/enrollments/$id',
  path: '/student/enrollments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCoursesIdRoute = StudentCoursesIdRouteImport.update({
  id: '/student/courses/$id',
  path: '/student/courses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorLessonsIdRoute = InstructorLessonsIdRouteImport.update({
  id: '/instructor/lessons/$id',
  path: '/instructor/lessons/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorCoursesIdRoute = InstructorCoursesIdRouteImport.update({
  id: '/instructor/courses/$id',
  path: '/instructor/courses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsIdRoute = AdminStudentsIdRouteImport.update({
  id: '/admin/students/$id',
  path: '/admin/students/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInstructorsIdRoute = AdminInstructorsIdRouteImport.update({
  id: '/admin/instructors/$id',
  path: '/admin/instructors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesIdRoute = AdminCoursesIdRouteImport.update({
  id: '/admin/courses/$id',
  path: '/admin/courses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthRegisterRoute = AdminAuthRegisterRouteImport.update({
  id: '/admin/auth/register',
  path: '/admin/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthLoginRoute = AdminAuthLoginRouteImport.update({
  id: '/admin/auth/login',
  path: '/admin/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorLessonsNewIndexRoute =
  InstructorLessonsNewIndexRouteImport.update({
    id: '/instructor/lessons/new/',
    path: '/instructor/lessons/new/',
    getParentRoute: () => rootRouteImport,
  } as any)
const InstructorCoursesNewIndexRoute =
  InstructorCoursesNewIndexRouteImport.update({
    id: '/instructor/courses/new/',
    path: '/instructor/courses/new/',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentEnrollmentsLessonsIdRoute =
  StudentEnrollmentsLessonsIdRouteImport.update({
    id: '/student/enrollments/lessons/$id',
    path: '/student/enrollments/lessons/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/instructor': typeof InstructorIndexRoute
  '/landing-page': typeof LandingPageIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/student': typeof StudentIndexRoute
  '/admin/auth/login': typeof AdminAuthLoginRoute
  '/admin/auth/register': typeof AdminAuthRegisterRoute
  '/admin/courses/$id': typeof AdminCoursesIdRoute
  '/admin/instructors/$id': typeof AdminInstructorsIdRoute
  '/admin/students/$id': typeof AdminStudentsIdRoute
  '/instructor/courses/$id': typeof InstructorCoursesIdRoute
  '/instructor/lessons/$id': typeof InstructorLessonsIdRoute
  '/student/courses/$id': typeof StudentCoursesIdRoute
  '/student/enrollments/$id': typeof StudentEnrollmentsIdRoute
  '/admin/admins': typeof AdminAdminsIndexRoute
  '/admin/analytics': typeof AdminAnalyticsIndexRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
  '/admin/instructors': typeof AdminInstructorsIndexRoute
  '/admin/profile': typeof AdminProfileIndexRoute
  '/admin/students': typeof AdminStudentsIndexRoute
  '/instructor/analytics': typeof InstructorAnalyticsIndexRoute
  '/instructor/assignments': typeof InstructorAssignmentsIndexRoute
  '/instructor/courses': typeof InstructorCoursesIndexRoute
  '/instructor/earnings': typeof InstructorEarningsIndexRoute
  '/instructor/lessons': typeof InstructorLessonsIndexRoute
  '/instructor/students': typeof InstructorStudentsIndexRoute
  '/student/analytics': typeof StudentAnalyticsIndexRoute
  '/student/assigments': typeof StudentAssigmentsIndexRoute
  '/student/courses': typeof StudentCoursesIndexRoute
  '/student/enrollments': typeof StudentEnrollmentsIndexRoute
  '/student/payments': typeof StudentPaymentsIndexRoute
  '/student/enrollments/lessons/$id': typeof StudentEnrollmentsLessonsIdRoute
  '/instructor/courses/new': typeof InstructorCoursesNewIndexRoute
  '/instructor/lessons/new': typeof InstructorLessonsNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/instructor': typeof InstructorIndexRoute
  '/landing-page': typeof LandingPageIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/student': typeof StudentIndexRoute
  '/admin/auth/login': typeof AdminAuthLoginRoute
  '/admin/auth/register': typeof AdminAuthRegisterRoute
  '/admin/courses/$id': typeof AdminCoursesIdRoute
  '/admin/instructors/$id': typeof AdminInstructorsIdRoute
  '/admin/students/$id': typeof AdminStudentsIdRoute
  '/instructor/courses/$id': typeof InstructorCoursesIdRoute
  '/instructor/lessons/$id': typeof InstructorLessonsIdRoute
  '/student/courses/$id': typeof StudentCoursesIdRoute
  '/student/enrollments/$id': typeof StudentEnrollmentsIdRoute
  '/admin/admins': typeof AdminAdminsIndexRoute
  '/admin/analytics': typeof AdminAnalyticsIndexRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
  '/admin/instructors': typeof AdminInstructorsIndexRoute
  '/admin/profile': typeof AdminProfileIndexRoute
  '/admin/students': typeof AdminStudentsIndexRoute
  '/instructor/analytics': typeof InstructorAnalyticsIndexRoute
  '/instructor/assignments': typeof InstructorAssignmentsIndexRoute
  '/instructor/courses': typeof InstructorCoursesIndexRoute
  '/instructor/earnings': typeof InstructorEarningsIndexRoute
  '/instructor/lessons': typeof InstructorLessonsIndexRoute
  '/instructor/students': typeof InstructorStudentsIndexRoute
  '/student/analytics': typeof StudentAnalyticsIndexRoute
  '/student/assigments': typeof StudentAssigmentsIndexRoute
  '/student/courses': typeof StudentCoursesIndexRoute
  '/student/enrollments': typeof StudentEnrollmentsIndexRoute
  '/student/payments': typeof StudentPaymentsIndexRoute
  '/student/enrollments/lessons/$id': typeof StudentEnrollmentsLessonsIdRoute
  '/instructor/courses/new': typeof InstructorCoursesNewIndexRoute
  '/instructor/lessons/new': typeof InstructorLessonsNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/instructor/': typeof InstructorIndexRoute
  '/landing-page/': typeof LandingPageIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/student/': typeof StudentIndexRoute
  '/admin/auth/login': typeof AdminAuthLoginRoute
  '/admin/auth/register': typeof AdminAuthRegisterRoute
  '/admin/courses/$id': typeof AdminCoursesIdRoute
  '/admin/instructors/$id': typeof AdminInstructorsIdRoute
  '/admin/students/$id': typeof AdminStudentsIdRoute
  '/instructor/courses/$id': typeof InstructorCoursesIdRoute
  '/instructor/lessons/$id': typeof InstructorLessonsIdRoute
  '/student/courses/$id': typeof StudentCoursesIdRoute
  '/student/enrollments/$id': typeof StudentEnrollmentsIdRoute
  '/admin/admins/': typeof AdminAdminsIndexRoute
  '/admin/analytics/': typeof AdminAnalyticsIndexRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/instructors/': typeof AdminInstructorsIndexRoute
  '/admin/profile/': typeof AdminProfileIndexRoute
  '/admin/students/': typeof AdminStudentsIndexRoute
  '/instructor/analytics/': typeof InstructorAnalyticsIndexRoute
  '/instructor/assignments/': typeof InstructorAssignmentsIndexRoute
  '/instructor/courses/': typeof InstructorCoursesIndexRoute
  '/instructor/earnings/': typeof InstructorEarningsIndexRoute
  '/instructor/lessons/': typeof InstructorLessonsIndexRoute
  '/instructor/students/': typeof InstructorStudentsIndexRoute
  '/student/analytics/': typeof StudentAnalyticsIndexRoute
  '/student/assigments/': typeof StudentAssigmentsIndexRoute
  '/student/courses/': typeof StudentCoursesIndexRoute
  '/student/enrollments/': typeof StudentEnrollmentsIndexRoute
  '/student/payments/': typeof StudentPaymentsIndexRoute
  '/student/enrollments/lessons/$id': typeof StudentEnrollmentsLessonsIdRoute
  '/instructor/courses/new/': typeof InstructorCoursesNewIndexRoute
  '/instructor/lessons/new/': typeof InstructorLessonsNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth/login'
    | '/auth/register'
    | '/instructor'
    | '/landing-page'
    | '/profile'
    | '/settings'
    | '/student'
    | '/admin/auth/login'
    | '/admin/auth/register'
    | '/admin/courses/$id'
    | '/admin/instructors/$id'
    | '/admin/students/$id'
    | '/instructor/courses/$id'
    | '/instructor/lessons/$id'
    | '/student/courses/$id'
    | '/student/enrollments/$id'
    | '/admin/admins'
    | '/admin/analytics'
    | '/admin/courses'
    | '/admin/instructors'
    | '/admin/profile'
    | '/admin/students'
    | '/instructor/analytics'
    | '/instructor/assignments'
    | '/instructor/courses'
    | '/instructor/earnings'
    | '/instructor/lessons'
    | '/instructor/students'
    | '/student/analytics'
    | '/student/assigments'
    | '/student/courses'
    | '/student/enrollments'
    | '/student/payments'
    | '/student/enrollments/lessons/$id'
    | '/instructor/courses/new'
    | '/instructor/lessons/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth/login'
    | '/auth/register'
    | '/instructor'
    | '/landing-page'
    | '/profile'
    | '/settings'
    | '/student'
    | '/admin/auth/login'
    | '/admin/auth/register'
    | '/admin/courses/$id'
    | '/admin/instructors/$id'
    | '/admin/students/$id'
    | '/instructor/courses/$id'
    | '/instructor/lessons/$id'
    | '/student/courses/$id'
    | '/student/enrollments/$id'
    | '/admin/admins'
    | '/admin/analytics'
    | '/admin/courses'
    | '/admin/instructors'
    | '/admin/profile'
    | '/admin/students'
    | '/instructor/analytics'
    | '/instructor/assignments'
    | '/instructor/courses'
    | '/instructor/earnings'
    | '/instructor/lessons'
    | '/instructor/students'
    | '/student/analytics'
    | '/student/assigments'
    | '/student/courses'
    | '/student/enrollments'
    | '/student/payments'
    | '/student/enrollments/lessons/$id'
    | '/instructor/courses/new'
    | '/instructor/lessons/new'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth/login'
    | '/auth/register'
    | '/instructor/'
    | '/landing-page/'
    | '/profile/'
    | '/settings/'
    | '/student/'
    | '/admin/auth/login'
    | '/admin/auth/register'
    | '/admin/courses/$id'
    | '/admin/instructors/$id'
    | '/admin/students/$id'
    | '/instructor/courses/$id'
    | '/instructor/lessons/$id'
    | '/student/courses/$id'
    | '/student/enrollments/$id'
    | '/admin/admins/'
    | '/admin/analytics/'
    | '/admin/courses/'
    | '/admin/instructors/'
    | '/admin/profile/'
    | '/admin/students/'
    | '/instructor/analytics/'
    | '/instructor/assignments/'
    | '/instructor/courses/'
    | '/instructor/earnings/'
    | '/instructor/lessons/'
    | '/instructor/students/'
    | '/student/analytics/'
    | '/student/assigments/'
    | '/student/courses/'
    | '/student/enrollments/'
    | '/student/payments/'
    | '/student/enrollments/lessons/$id'
    | '/instructor/courses/new/'
    | '/instructor/lessons/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  InstructorIndexRoute: typeof InstructorIndexRoute
  LandingPageIndexRoute: typeof LandingPageIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  StudentIndexRoute: typeof StudentIndexRoute
  AdminAuthLoginRoute: typeof AdminAuthLoginRoute
  AdminAuthRegisterRoute: typeof AdminAuthRegisterRoute
  AdminCoursesIdRoute: typeof AdminCoursesIdRoute
  AdminInstructorsIdRoute: typeof AdminInstructorsIdRoute
  AdminStudentsIdRoute: typeof AdminStudentsIdRoute
  InstructorCoursesIdRoute: typeof InstructorCoursesIdRoute
  InstructorLessonsIdRoute: typeof InstructorLessonsIdRoute
  StudentCoursesIdRoute: typeof StudentCoursesIdRoute
  StudentEnrollmentsIdRoute: typeof StudentEnrollmentsIdRoute
  AdminAdminsIndexRoute: typeof AdminAdminsIndexRoute
  AdminAnalyticsIndexRoute: typeof AdminAnalyticsIndexRoute
  AdminCoursesIndexRoute: typeof AdminCoursesIndexRoute
  AdminInstructorsIndexRoute: typeof AdminInstructorsIndexRoute
  AdminProfileIndexRoute: typeof AdminProfileIndexRoute
  AdminStudentsIndexRoute: typeof AdminStudentsIndexRoute
  InstructorAnalyticsIndexRoute: typeof InstructorAnalyticsIndexRoute
  InstructorAssignmentsIndexRoute: typeof InstructorAssignmentsIndexRoute
  InstructorCoursesIndexRoute: typeof InstructorCoursesIndexRoute
  InstructorEarningsIndexRoute: typeof InstructorEarningsIndexRoute
  InstructorLessonsIndexRoute: typeof InstructorLessonsIndexRoute
  InstructorStudentsIndexRoute: typeof InstructorStudentsIndexRoute
  StudentAnalyticsIndexRoute: typeof StudentAnalyticsIndexRoute
  StudentAssigmentsIndexRoute: typeof StudentAssigmentsIndexRoute
  StudentCoursesIndexRoute: typeof StudentCoursesIndexRoute
  StudentEnrollmentsIndexRoute: typeof StudentEnrollmentsIndexRoute
  StudentPaymentsIndexRoute: typeof StudentPaymentsIndexRoute
  StudentEnrollmentsLessonsIdRoute: typeof StudentEnrollmentsLessonsIdRoute
  InstructorCoursesNewIndexRoute: typeof InstructorCoursesNewIndexRoute
  InstructorLessonsNewIndexRoute: typeof InstructorLessonsNewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing-page/': {
      id: '/landing-page/'
      path: '/landing-page'
      fullPath: '/landing-page'
      preLoaderRoute: typeof LandingPageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/': {
      id: '/instructor/'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/payments/': {
      id: '/student/payments/'
      path: '/student/payments'
      fullPath: '/student/payments'
      preLoaderRoute: typeof StudentPaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/enrollments/': {
      id: '/student/enrollments/'
      path: '/student/enrollments'
      fullPath: '/student/enrollments'
      preLoaderRoute: typeof StudentEnrollmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/courses/': {
      id: '/student/courses/'
      path: '/student/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/assigments/': {
      id: '/student/assigments/'
      path: '/student/assigments'
      fullPath: '/student/assigments'
      preLoaderRoute: typeof StudentAssigmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/analytics/': {
      id: '/student/analytics/'
      path: '/student/analytics'
      fullPath: '/student/analytics'
      preLoaderRoute: typeof StudentAnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/students/': {
      id: '/instructor/students/'
      path: '/instructor/students'
      fullPath: '/instructor/students'
      preLoaderRoute: typeof InstructorStudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/lessons/': {
      id: '/instructor/lessons/'
      path: '/instructor/lessons'
      fullPath: '/instructor/lessons'
      preLoaderRoute: typeof InstructorLessonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/earnings/': {
      id: '/instructor/earnings/'
      path: '/instructor/earnings'
      fullPath: '/instructor/earnings'
      preLoaderRoute: typeof InstructorEarningsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/courses/': {
      id: '/instructor/courses/'
      path: '/instructor/courses'
      fullPath: '/instructor/courses'
      preLoaderRoute: typeof InstructorCoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/assignments/': {
      id: '/instructor/assignments/'
      path: '/instructor/assignments'
      fullPath: '/instructor/assignments'
      preLoaderRoute: typeof InstructorAssignmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/analytics/': {
      id: '/instructor/analytics/'
      path: '/instructor/analytics'
      fullPath: '/instructor/analytics'
      preLoaderRoute: typeof InstructorAnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students/': {
      id: '/admin/students/'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile/': {
      id: '/admin/profile/'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/instructors/': {
      id: '/admin/instructors/'
      path: '/admin/instructors'
      fullPath: '/admin/instructors'
      preLoaderRoute: typeof AdminInstructorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses/': {
      id: '/admin/courses/'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics/': {
      id: '/admin/analytics/'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/admins/': {
      id: '/admin/admins/'
      path: '/admin/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/enrollments/$id': {
      id: '/student/enrollments/$id'
      path: '/student/enrollments/$id'
      fullPath: '/student/enrollments/$id'
      preLoaderRoute: typeof StudentEnrollmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/courses/$id': {
      id: '/student/courses/$id'
      path: '/student/courses/$id'
      fullPath: '/student/courses/$id'
      preLoaderRoute: typeof StudentCoursesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/lessons/$id': {
      id: '/instructor/lessons/$id'
      path: '/instructor/lessons/$id'
      fullPath: '/instructor/lessons/$id'
      preLoaderRoute: typeof InstructorLessonsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/courses/$id': {
      id: '/instructor/courses/$id'
      path: '/instructor/courses/$id'
      fullPath: '/instructor/courses/$id'
      preLoaderRoute: typeof InstructorCoursesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students/$id': {
      id: '/admin/students/$id'
      path: '/admin/students/$id'
      fullPath: '/admin/students/$id'
      preLoaderRoute: typeof AdminStudentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/instructors/$id': {
      id: '/admin/instructors/$id'
      path: '/admin/instructors/$id'
      fullPath: '/admin/instructors/$id'
      preLoaderRoute: typeof AdminInstructorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses/$id': {
      id: '/admin/courses/$id'
      path: '/admin/courses/$id'
      fullPath: '/admin/courses/$id'
      preLoaderRoute: typeof AdminCoursesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/auth/register': {
      id: '/admin/auth/register'
      path: '/admin/auth/register'
      fullPath: '/admin/auth/register'
      preLoaderRoute: typeof AdminAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/auth/login': {
      id: '/admin/auth/login'
      path: '/admin/auth/login'
      fullPath: '/admin/auth/login'
      preLoaderRoute: typeof AdminAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/lessons/new/': {
      id: '/instructor/lessons/new/'
      path: '/instructor/lessons/new'
      fullPath: '/instructor/lessons/new'
      preLoaderRoute: typeof InstructorLessonsNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/courses/new/': {
      id: '/instructor/courses/new/'
      path: '/instructor/courses/new'
      fullPath: '/instructor/courses/new'
      preLoaderRoute: typeof InstructorCoursesNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/enrollments/lessons/$id': {
      id: '/student/enrollments/lessons/$id'
      path: '/student/enrollments/lessons/$id'
      fullPath: '/student/enrollments/lessons/$id'
      preLoaderRoute: typeof StudentEnrollmentsLessonsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  InstructorIndexRoute: InstructorIndexRoute,
  LandingPageIndexRoute: LandingPageIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  StudentIndexRoute: StudentIndexRoute,
  AdminAuthLoginRoute: AdminAuthLoginRoute,
  AdminAuthRegisterRoute: AdminAuthRegisterRoute,
  AdminCoursesIdRoute: AdminCoursesIdRoute,
  AdminInstructorsIdRoute: AdminInstructorsIdRoute,
  AdminStudentsIdRoute: AdminStudentsIdRoute,
  InstructorCoursesIdRoute: InstructorCoursesIdRoute,
  InstructorLessonsIdRoute: InstructorLessonsIdRoute,
  StudentCoursesIdRoute: StudentCoursesIdRoute,
  StudentEnrollmentsIdRoute: StudentEnrollmentsIdRoute,
  AdminAdminsIndexRoute: AdminAdminsIndexRoute,
  AdminAnalyticsIndexRoute: AdminAnalyticsIndexRoute,
  AdminCoursesIndexRoute: AdminCoursesIndexRoute,
  AdminInstructorsIndexRoute: AdminInstructorsIndexRoute,
  AdminProfileIndexRoute: AdminProfileIndexRoute,
  AdminStudentsIndexRoute: AdminStudentsIndexRoute,
  InstructorAnalyticsIndexRoute: InstructorAnalyticsIndexRoute,
  InstructorAssignmentsIndexRoute: InstructorAssignmentsIndexRoute,
  InstructorCoursesIndexRoute: InstructorCoursesIndexRoute,
  InstructorEarningsIndexRoute: InstructorEarningsIndexRoute,
  InstructorLessonsIndexRoute: InstructorLessonsIndexRoute,
  InstructorStudentsIndexRoute: InstructorStudentsIndexRoute,
  StudentAnalyticsIndexRoute: StudentAnalyticsIndexRoute,
  StudentAssigmentsIndexRoute: StudentAssigmentsIndexRoute,
  StudentCoursesIndexRoute: StudentCoursesIndexRoute,
  StudentEnrollmentsIndexRoute: StudentEnrollmentsIndexRoute,
  StudentPaymentsIndexRoute: StudentPaymentsIndexRoute,
  StudentEnrollmentsLessonsIdRoute: StudentEnrollmentsLessonsIdRoute,
  InstructorCoursesNewIndexRoute: InstructorCoursesNewIndexRoute,
  InstructorLessonsNewIndexRoute: InstructorLessonsNewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
