/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as LandingPageIndexRouteImport } from './routes/landing-page/index'
import { Route as InstructorIndexRouteImport } from './routes/instructor/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as StudentSettingsIndexRouteImport } from './routes/student/settings/index'
import { Route as StudentProfileIndexRouteImport } from './routes/student/profile/index'
import { Route as StudentMyCoursesIndexRouteImport } from './routes/student/my-courses/index'
import { Route as StudentEnrollmentsIndexRouteImport } from './routes/student/enrollments/index'
import { Route as StudentCoursesIndexRouteImport } from './routes/student/courses/index'
import { Route as StudentAssigmentsIndexRouteImport } from './routes/student/assigments/index'
import { Route as InstructorStudentsIndexRouteImport } from './routes/instructor/students/index'
import { Route as InstructorSettingsIndexRouteImport } from './routes/instructor/settings/index'
import { Route as InstructorProfileIndexRouteImport } from './routes/instructor/profile/index'
import { Route as InstructorLessonsIndexRouteImport } from './routes/instructor/lessons/index'
import { Route as InstructorEarningsIndexRouteImport } from './routes/instructor/earnings/index'
import { Route as InstructorCoursesIndexRouteImport } from './routes/instructor/courses/index'
import { Route as InstructorAssignmentsIndexRouteImport } from './routes/instructor/assignments/index'
import { Route as InstructorAnalyticsIndexRouteImport } from './routes/instructor/analytics/index'
import { Route as StudentEnrollmentsIdRouteImport } from './routes/student/enrollments/$id'
import { Route as StudentCoursesIdRouteImport } from './routes/student/courses/$id'
import { Route as InstructorLessonsIdRouteImport } from './routes/instructor/lessons/$id'
import { Route as InstructorCoursesIdRouteImport } from './routes/instructor/courses/$id'
import { Route as InstructorLessonsNewIndexRouteImport } from './routes/instructor/lessons/new/index'
import { Route as InstructorCoursesNewIndexRouteImport } from './routes/instructor/courses/new/index'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingPageIndexRoute = LandingPageIndexRouteImport.update({
  id: '/landing-page/',
  path: '/landing-page/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorIndexRoute = InstructorIndexRouteImport.update({
  id: '/instructor/',
  path: '/instructor/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentSettingsIndexRoute = StudentSettingsIndexRouteImport.update({
  id: '/student/settings/',
  path: '/student/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProfileIndexRoute = StudentProfileIndexRouteImport.update({
  id: '/student/profile/',
  path: '/student/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentMyCoursesIndexRoute = StudentMyCoursesIndexRouteImport.update({
  id: '/student/my-courses/',
  path: '/student/my-courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentEnrollmentsIndexRoute = StudentEnrollmentsIndexRouteImport.update({
  id: '/student/enrollments/',
  path: '/student/enrollments/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCoursesIndexRoute = StudentCoursesIndexRouteImport.update({
  id: '/student/courses/',
  path: '/student/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAssigmentsIndexRoute = StudentAssigmentsIndexRouteImport.update({
  id: '/student/assigments/',
  path: '/student/assigments/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorStudentsIndexRoute = InstructorStudentsIndexRouteImport.update({
  id: '/instructor/students/',
  path: '/instructor/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorSettingsIndexRoute = InstructorSettingsIndexRouteImport.update({
  id: '/instructor/settings/',
  path: '/instructor/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorProfileIndexRoute = InstructorProfileIndexRouteImport.update({
  id: '/instructor/profile/',
  path: '/instructor/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorLessonsIndexRoute = InstructorLessonsIndexRouteImport.update({
  id: '/instructor/lessons/',
  path: '/instructor/lessons/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorEarningsIndexRoute = InstructorEarningsIndexRouteImport.update({
  id: '/instructor/earnings/',
  path: '/instructor/earnings/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorCoursesIndexRoute = InstructorCoursesIndexRouteImport.update({
  id: '/instructor/courses/',
  path: '/instructor/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorAssignmentsIndexRoute =
  InstructorAssignmentsIndexRouteImport.update({
    id: '/instructor/assignments/',
    path: '/instructor/assignments/',
    getParentRoute: () => rootRouteImport,
  } as any)
const InstructorAnalyticsIndexRoute =
  InstructorAnalyticsIndexRouteImport.update({
    id: '/instructor/analytics/',
    path: '/instructor/analytics/',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentEnrollmentsIdRoute = StudentEnrollmentsIdRouteImport.update({
  id: '/student/enrollments/$id',
  path: '/student/enrollments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCoursesIdRoute = StudentCoursesIdRouteImport.update({
  id: '/student/courses/$id',
  path: '/student/courses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorLessonsIdRoute = InstructorLessonsIdRouteImport.update({
  id: '/instructor/lessons/$id',
  path: '/instructor/lessons/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorCoursesIdRoute = InstructorCoursesIdRouteImport.update({
  id: '/instructor/courses/$id',
  path: '/instructor/courses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorLessonsNewIndexRoute =
  InstructorLessonsNewIndexRouteImport.update({
    id: '/instructor/lessons/new/',
    path: '/instructor/lessons/new/',
    getParentRoute: () => rootRouteImport,
  } as any)
const InstructorCoursesNewIndexRoute =
  InstructorCoursesNewIndexRouteImport.update({
    id: '/instructor/courses/new/',
    path: '/instructor/courses/new/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/instructor': typeof InstructorIndexRoute
  '/landing-page': typeof LandingPageIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/student': typeof StudentIndexRoute
  '/instructor/courses/$id': typeof InstructorCoursesIdRoute
  '/instructor/lessons/$id': typeof InstructorLessonsIdRoute
  '/student/courses/$id': typeof StudentCoursesIdRoute
  '/student/enrollments/$id': typeof StudentEnrollmentsIdRoute
  '/instructor/analytics': typeof InstructorAnalyticsIndexRoute
  '/instructor/assignments': typeof InstructorAssignmentsIndexRoute
  '/instructor/courses': typeof InstructorCoursesIndexRoute
  '/instructor/earnings': typeof InstructorEarningsIndexRoute
  '/instructor/lessons': typeof InstructorLessonsIndexRoute
  '/instructor/profile': typeof InstructorProfileIndexRoute
  '/instructor/settings': typeof InstructorSettingsIndexRoute
  '/instructor/students': typeof InstructorStudentsIndexRoute
  '/student/assigments': typeof StudentAssigmentsIndexRoute
  '/student/courses': typeof StudentCoursesIndexRoute
  '/student/enrollments': typeof StudentEnrollmentsIndexRoute
  '/student/my-courses': typeof StudentMyCoursesIndexRoute
  '/student/profile': typeof StudentProfileIndexRoute
  '/student/settings': typeof StudentSettingsIndexRoute
  '/instructor/courses/new': typeof InstructorCoursesNewIndexRoute
  '/instructor/lessons/new': typeof InstructorLessonsNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/instructor': typeof InstructorIndexRoute
  '/landing-page': typeof LandingPageIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/student': typeof StudentIndexRoute
  '/instructor/courses/$id': typeof InstructorCoursesIdRoute
  '/instructor/lessons/$id': typeof InstructorLessonsIdRoute
  '/student/courses/$id': typeof StudentCoursesIdRoute
  '/student/enrollments/$id': typeof StudentEnrollmentsIdRoute
  '/instructor/analytics': typeof InstructorAnalyticsIndexRoute
  '/instructor/assignments': typeof InstructorAssignmentsIndexRoute
  '/instructor/courses': typeof InstructorCoursesIndexRoute
  '/instructor/earnings': typeof InstructorEarningsIndexRoute
  '/instructor/lessons': typeof InstructorLessonsIndexRoute
  '/instructor/profile': typeof InstructorProfileIndexRoute
  '/instructor/settings': typeof InstructorSettingsIndexRoute
  '/instructor/students': typeof InstructorStudentsIndexRoute
  '/student/assigments': typeof StudentAssigmentsIndexRoute
  '/student/courses': typeof StudentCoursesIndexRoute
  '/student/enrollments': typeof StudentEnrollmentsIndexRoute
  '/student/my-courses': typeof StudentMyCoursesIndexRoute
  '/student/profile': typeof StudentProfileIndexRoute
  '/student/settings': typeof StudentSettingsIndexRoute
  '/instructor/courses/new': typeof InstructorCoursesNewIndexRoute
  '/instructor/lessons/new': typeof InstructorLessonsNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/instructor/': typeof InstructorIndexRoute
  '/landing-page/': typeof LandingPageIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/student/': typeof StudentIndexRoute
  '/instructor/courses/$id': typeof InstructorCoursesIdRoute
  '/instructor/lessons/$id': typeof InstructorLessonsIdRoute
  '/student/courses/$id': typeof StudentCoursesIdRoute
  '/student/enrollments/$id': typeof StudentEnrollmentsIdRoute
  '/instructor/analytics/': typeof InstructorAnalyticsIndexRoute
  '/instructor/assignments/': typeof InstructorAssignmentsIndexRoute
  '/instructor/courses/': typeof InstructorCoursesIndexRoute
  '/instructor/earnings/': typeof InstructorEarningsIndexRoute
  '/instructor/lessons/': typeof InstructorLessonsIndexRoute
  '/instructor/profile/': typeof InstructorProfileIndexRoute
  '/instructor/settings/': typeof InstructorSettingsIndexRoute
  '/instructor/students/': typeof InstructorStudentsIndexRoute
  '/student/assigments/': typeof StudentAssigmentsIndexRoute
  '/student/courses/': typeof StudentCoursesIndexRoute
  '/student/enrollments/': typeof StudentEnrollmentsIndexRoute
  '/student/my-courses/': typeof StudentMyCoursesIndexRoute
  '/student/profile/': typeof StudentProfileIndexRoute
  '/student/settings/': typeof StudentSettingsIndexRoute
  '/instructor/courses/new/': typeof InstructorCoursesNewIndexRoute
  '/instructor/lessons/new/': typeof InstructorLessonsNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth/login'
    | '/auth/register'
    | '/instructor'
    | '/landing-page'
    | '/profile'
    | '/settings'
    | '/student'
    | '/instructor/courses/$id'
    | '/instructor/lessons/$id'
    | '/student/courses/$id'
    | '/student/enrollments/$id'
    | '/instructor/analytics'
    | '/instructor/assignments'
    | '/instructor/courses'
    | '/instructor/earnings'
    | '/instructor/lessons'
    | '/instructor/profile'
    | '/instructor/settings'
    | '/instructor/students'
    | '/student/assigments'
    | '/student/courses'
    | '/student/enrollments'
    | '/student/my-courses'
    | '/student/profile'
    | '/student/settings'
    | '/instructor/courses/new'
    | '/instructor/lessons/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth/login'
    | '/auth/register'
    | '/instructor'
    | '/landing-page'
    | '/profile'
    | '/settings'
    | '/student'
    | '/instructor/courses/$id'
    | '/instructor/lessons/$id'
    | '/student/courses/$id'
    | '/student/enrollments/$id'
    | '/instructor/analytics'
    | '/instructor/assignments'
    | '/instructor/courses'
    | '/instructor/earnings'
    | '/instructor/lessons'
    | '/instructor/profile'
    | '/instructor/settings'
    | '/instructor/students'
    | '/student/assigments'
    | '/student/courses'
    | '/student/enrollments'
    | '/student/my-courses'
    | '/student/profile'
    | '/student/settings'
    | '/instructor/courses/new'
    | '/instructor/lessons/new'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth/login'
    | '/auth/register'
    | '/instructor/'
    | '/landing-page/'
    | '/profile/'
    | '/settings/'
    | '/student/'
    | '/instructor/courses/$id'
    | '/instructor/lessons/$id'
    | '/student/courses/$id'
    | '/student/enrollments/$id'
    | '/instructor/analytics/'
    | '/instructor/assignments/'
    | '/instructor/courses/'
    | '/instructor/earnings/'
    | '/instructor/lessons/'
    | '/instructor/profile/'
    | '/instructor/settings/'
    | '/instructor/students/'
    | '/student/assigments/'
    | '/student/courses/'
    | '/student/enrollments/'
    | '/student/my-courses/'
    | '/student/profile/'
    | '/student/settings/'
    | '/instructor/courses/new/'
    | '/instructor/lessons/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  InstructorIndexRoute: typeof InstructorIndexRoute
  LandingPageIndexRoute: typeof LandingPageIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  StudentIndexRoute: typeof StudentIndexRoute
  InstructorCoursesIdRoute: typeof InstructorCoursesIdRoute
  InstructorLessonsIdRoute: typeof InstructorLessonsIdRoute
  StudentCoursesIdRoute: typeof StudentCoursesIdRoute
  StudentEnrollmentsIdRoute: typeof StudentEnrollmentsIdRoute
  InstructorAnalyticsIndexRoute: typeof InstructorAnalyticsIndexRoute
  InstructorAssignmentsIndexRoute: typeof InstructorAssignmentsIndexRoute
  InstructorCoursesIndexRoute: typeof InstructorCoursesIndexRoute
  InstructorEarningsIndexRoute: typeof InstructorEarningsIndexRoute
  InstructorLessonsIndexRoute: typeof InstructorLessonsIndexRoute
  InstructorProfileIndexRoute: typeof InstructorProfileIndexRoute
  InstructorSettingsIndexRoute: typeof InstructorSettingsIndexRoute
  InstructorStudentsIndexRoute: typeof InstructorStudentsIndexRoute
  StudentAssigmentsIndexRoute: typeof StudentAssigmentsIndexRoute
  StudentCoursesIndexRoute: typeof StudentCoursesIndexRoute
  StudentEnrollmentsIndexRoute: typeof StudentEnrollmentsIndexRoute
  StudentMyCoursesIndexRoute: typeof StudentMyCoursesIndexRoute
  StudentProfileIndexRoute: typeof StudentProfileIndexRoute
  StudentSettingsIndexRoute: typeof StudentSettingsIndexRoute
  InstructorCoursesNewIndexRoute: typeof InstructorCoursesNewIndexRoute
  InstructorLessonsNewIndexRoute: typeof InstructorLessonsNewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing-page/': {
      id: '/landing-page/'
      path: '/landing-page'
      fullPath: '/landing-page'
      preLoaderRoute: typeof LandingPageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/': {
      id: '/instructor/'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/settings/': {
      id: '/student/settings/'
      path: '/student/settings'
      fullPath: '/student/settings'
      preLoaderRoute: typeof StudentSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/profile/': {
      id: '/student/profile/'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/my-courses/': {
      id: '/student/my-courses/'
      path: '/student/my-courses'
      fullPath: '/student/my-courses'
      preLoaderRoute: typeof StudentMyCoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/enrollments/': {
      id: '/student/enrollments/'
      path: '/student/enrollments'
      fullPath: '/student/enrollments'
      preLoaderRoute: typeof StudentEnrollmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/courses/': {
      id: '/student/courses/'
      path: '/student/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/assigments/': {
      id: '/student/assigments/'
      path: '/student/assigments'
      fullPath: '/student/assigments'
      preLoaderRoute: typeof StudentAssigmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/students/': {
      id: '/instructor/students/'
      path: '/instructor/students'
      fullPath: '/instructor/students'
      preLoaderRoute: typeof InstructorStudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/settings/': {
      id: '/instructor/settings/'
      path: '/instructor/settings'
      fullPath: '/instructor/settings'
      preLoaderRoute: typeof InstructorSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/profile/': {
      id: '/instructor/profile/'
      path: '/instructor/profile'
      fullPath: '/instructor/profile'
      preLoaderRoute: typeof InstructorProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/lessons/': {
      id: '/instructor/lessons/'
      path: '/instructor/lessons'
      fullPath: '/instructor/lessons'
      preLoaderRoute: typeof InstructorLessonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/earnings/': {
      id: '/instructor/earnings/'
      path: '/instructor/earnings'
      fullPath: '/instructor/earnings'
      preLoaderRoute: typeof InstructorEarningsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/courses/': {
      id: '/instructor/courses/'
      path: '/instructor/courses'
      fullPath: '/instructor/courses'
      preLoaderRoute: typeof InstructorCoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/assignments/': {
      id: '/instructor/assignments/'
      path: '/instructor/assignments'
      fullPath: '/instructor/assignments'
      preLoaderRoute: typeof InstructorAssignmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/analytics/': {
      id: '/instructor/analytics/'
      path: '/instructor/analytics'
      fullPath: '/instructor/analytics'
      preLoaderRoute: typeof InstructorAnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/enrollments/$id': {
      id: '/student/enrollments/$id'
      path: '/student/enrollments/$id'
      fullPath: '/student/enrollments/$id'
      preLoaderRoute: typeof StudentEnrollmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/courses/$id': {
      id: '/student/courses/$id'
      path: '/student/courses/$id'
      fullPath: '/student/courses/$id'
      preLoaderRoute: typeof StudentCoursesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/lessons/$id': {
      id: '/instructor/lessons/$id'
      path: '/instructor/lessons/$id'
      fullPath: '/instructor/lessons/$id'
      preLoaderRoute: typeof InstructorLessonsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/courses/$id': {
      id: '/instructor/courses/$id'
      path: '/instructor/courses/$id'
      fullPath: '/instructor/courses/$id'
      preLoaderRoute: typeof InstructorCoursesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/lessons/new/': {
      id: '/instructor/lessons/new/'
      path: '/instructor/lessons/new'
      fullPath: '/instructor/lessons/new'
      preLoaderRoute: typeof InstructorLessonsNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/courses/new/': {
      id: '/instructor/courses/new/'
      path: '/instructor/courses/new'
      fullPath: '/instructor/courses/new'
      preLoaderRoute: typeof InstructorCoursesNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  InstructorIndexRoute: InstructorIndexRoute,
  LandingPageIndexRoute: LandingPageIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  StudentIndexRoute: StudentIndexRoute,
  InstructorCoursesIdRoute: InstructorCoursesIdRoute,
  InstructorLessonsIdRoute: InstructorLessonsIdRoute,
  StudentCoursesIdRoute: StudentCoursesIdRoute,
  StudentEnrollmentsIdRoute: StudentEnrollmentsIdRoute,
  InstructorAnalyticsIndexRoute: InstructorAnalyticsIndexRoute,
  InstructorAssignmentsIndexRoute: InstructorAssignmentsIndexRoute,
  InstructorCoursesIndexRoute: InstructorCoursesIndexRoute,
  InstructorEarningsIndexRoute: InstructorEarningsIndexRoute,
  InstructorLessonsIndexRoute: InstructorLessonsIndexRoute,
  InstructorProfileIndexRoute: InstructorProfileIndexRoute,
  InstructorSettingsIndexRoute: InstructorSettingsIndexRoute,
  InstructorStudentsIndexRoute: InstructorStudentsIndexRoute,
  StudentAssigmentsIndexRoute: StudentAssigmentsIndexRoute,
  StudentCoursesIndexRoute: StudentCoursesIndexRoute,
  StudentEnrollmentsIndexRoute: StudentEnrollmentsIndexRoute,
  StudentMyCoursesIndexRoute: StudentMyCoursesIndexRoute,
  StudentProfileIndexRoute: StudentProfileIndexRoute,
  StudentSettingsIndexRoute: StudentSettingsIndexRoute,
  InstructorCoursesNewIndexRoute: InstructorCoursesNewIndexRoute,
  InstructorLessonsNewIndexRoute: InstructorLessonsNewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
